
version: 2

sources:
  - name: redshift_source
    description: Gets data from redshift staging layer
    database: staging
    schema: public
    tables:
      - name: sales

models:
  - name: sales
    config:
      materialized: table
      alias: sales_rpt

